[package]
name = "essrpc"
version = "0.1.0"
authors = ["James Oakley <james@electronstudio.org>"]
description = "RPC using natural trait definitions and calls."
readme = "../README.md"
keywords = ["rpc"]
license = "MIT"
license-file = "../LICENSE"

[dependencies]
bincode = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
essrpc_macros = { path = "../essrpc_macros", version = "0.1.0" }
uuid = { version = "0.7", features = ["v4"] }
